In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
r=np.array((1,23,5,7,9))

In [4]:
a=np.array((4,7,8.90,2))

In [5]:
p=np.array({'name':'joe','marks':20})

In [6]:
id(r)

1755418984976

In [7]:
id(a)

1755380290768

In [8]:
id(p)

1755422675600

In [9]:
y=r

In [10]:
y

array([ 1, 23,  5,  7,  9])

In [11]:
id(y)

1755418984976

In [12]:
z=np.copy(a)


In [13]:
import numpy as np

In [14]:
a=([1,2,3,4])

In [15]:
p=a

In [16]:
id(a)

1755422779200

In [17]:
id(p)

1755422779200

In [18]:
z=np.copy(p)

In [19]:
id(z)

1755380290768

In [20]:
a=np.array({1:2,'name': 'joe', 'grade': 5, 'gpa': 4.2})

In [21]:
a

array({1: 2, 'name': 'joe', 'grade': 5, 'gpa': 4.2}, dtype=object)

In [22]:
z=np.array({1,2,3,4,5})

In [23]:
z

array({1, 2, 3, 4, 5}, dtype=object)

In [24]:
ap={1,2,3,4,5}

In [25]:
type(ap)

set

In [26]:
az={1,2,3,4,5,5,5,5,5}
az

{1, 2, 3, 4, 5}

In [27]:
arr1=([1,2,3,4])
arr1

[1, 2, 3, 4]

In [28]:
arr2=np.array([1,3.4,2.3,4,5,6])
arr2

array([1. , 3.4, 2.3, 4. , 5. , 6. ])

In [29]:
arr3=np.array([3,4,'5',6.7])
arr3

array(['3', '4', '5', '6.7'], dtype='<U32')

In [30]:
id(arr3)

1755422676560

In [31]:
arr5=arr3
id(arr5)

1755422676560

In [32]:
arr7=np.copy(arr3)
id(arr7)

1755422677232

In [33]:
q=np.array({2,4.5,'3',7,3.1,3.1,7.2})
q

array({2, 3.1, 4.5, 7.2, '3', 7}, dtype=object)

In [34]:
type(q)

numpy.ndarray

In [35]:
r=np.array((2,'3',8.9,0.75))
r

array(['2', '3', '8.9', '0.75'], dtype='<U32')

In [36]:
a=np.array({1:'joe',2:5.55,3:'245.33',4:8.9})
a

array({1: 'joe', 2: 5.55, 3: '245.33', 4: 8.9}, dtype=object)

In [37]:
[i for i in range(1,15)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [38]:
{i for i in range(1,15,4)}

{1, 5, 9, 13}

In [39]:
[i*2 for i in range(3,20,3)]

[6, 12, 18, 24, 30, 36]

In [40]:
n={i for i in range(10)}

In [41]:
n

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [42]:
c=['hello '+str(i) for i in range(2,10,2)]

In [43]:
c

['hello 2', 'hello 4', 'hello 6', 'hello 8']

In [44]:
g=[i for i in np.arange(10)]

In [45]:
g=np.arange(10) #1 parameter

In [46]:
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
type(g)

numpy.ndarray

In [48]:
h=np.arange(7)

In [49]:
v=np.arange(3,16)

In [50]:
v #2 parameter

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
type(v)

numpy.ndarray

In [52]:
type(n)

set

In [53]:
type(c)

list

In [54]:
x=np.arange(2,20,2)

In [55]:
x #3 parameter

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
g=np.arange(10) 
v=np.arange(-3,16)
x=np.arange(20,2,-2)

In [57]:
g


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
v

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15])

In [59]:
x

array([20, 18, 16, 14, 12, 10,  8,  6,  4])

In [60]:
j=np.arange(-24,-30,-1)
j

array([-24, -25, -26, -27, -28, -29])

In [61]:
[i%2!=0 for i in range(2,10)]

[False, True, False, True, False, True, False, True]

In [62]:
 np.array([2,3.4,'5',True,4.2])


array(['2', '3.4', '5', 'True', '4.2'], dtype='<U32')

In [63]:
 np.array([2,3.4,True,4.2])

array([2. , 3.4, 1. , 4.2])

In [64]:
 np.array([2,34,5,True,42])

array([ 2, 34,  5,  1, 42])