<a href="https://colab.research.google.com/github/VAMSHINEELAMMA/SAMSUNG-INNOVATION-CAMPUS/blob/main/ex_0307.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os

In [2]:
!wget --no-clobber https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_iris.csv

--2025-09-02 04:36:54--  https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3867 (3.8K) [text/plain]
Saving to: ‘data_iris.csv’

data_iris.csv       100%[===================>]   3.78K  --.-KB/s    in 0s      

2025-09-02 04:36:54 (56.5 MB/s) - ‘data_iris.csv’ saved [3867/3867]



In [3]:
# Read in the data.
df = pd.read_csv('data_iris.csv', header='infer')

In [4]:
df.shape

(150, 5)

In [5]:
df.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [6]:
# Set aside two variables.
x = df['Petal.Length']
y = df['Sepal.Length']

In [7]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.pearsonr(x,y),3)

array([0.872, 0.   ])

In [8]:
# Using the Pandas function.
x.corr(y)

np.float64(0.8717537758865831)

In [9]:
df1 = df.drop(['Species'], axis=1)

In [10]:
# Correlation array.
np.round(df1.corr(),3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length         1.000       -0.118         0.872        0.818
Sepal.Width         -0.118        1.000        -0.428       -0.366
Petal.Length         0.872       -0.428         1.000        0.963
Petal.Width          0.818       -0.366         0.963        1.000

In [11]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.spearmanr(x,y),3)

array([0.882, 0.   ])

In [12]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.kendalltau(x,y),3)         # Correlation coefficient and p-value.

array([0.719, 0.   ])

In [13]:
!wget --no-clobber https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_studentlist.csv

--2025-09-02 04:36:55--  https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_studentlist.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 674 [text/plain]
Saving to: ‘data_studentlist.csv’

data_studentlist.cs 100%[===================>]     674  --.-KB/s    in 0s      

2025-09-02 04:36:55 (47.6 MB/s) - ‘data_studentlist.csv’ saved [674/674]



In [14]:
# Read in another data set.
df = pd.read_csv('data_studentlist.csv', header='infer')

In [15]:
df.head(3)

name gender  age  grade absence bloodtype  height  weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [16]:
# Set aside two variables.
x = df.height
y = df.weight

In [17]:
# Apply the Fisher's z-transformation.
# See the lecture.
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [18]:
# 95% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': np.float64(0.26960396330592223),
 'high': np.float64(0.8677953581441814)}

In [19]:
# 99% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': np.float64(0.11137578298592947),
 'high': np.float64(0.9030812794020874)}