Pandas

In [2]:
import pandas as pd

In [3]:
pd.Series(['male','female','male','male','female','female'])

0      male
1    female
2      male
3      male
4    female
5    female
dtype: object

In [6]:
import numpy as np

In [10]:
a=pd.Series(np.array(['male','female','male','male','female','female']))

In [11]:
a

0      male
1    female
2      male
3      male
4    female
5    female
dtype: object

In [12]:
type(a)

pandas.core.series.Series

In [15]:
dict_data={'a': 1,'b': 2,'c': 3}

In [16]:
pd.Series(dict_data)

a    1
b    2
c    3
dtype: int64

In [17]:
b=pd.Series(dict_data)

In [18]:
type(b)

pandas.core.series.Series

In [22]:
b.index #displays keys in a dictionary

Index(['a', 'b', 'c'], dtype='object')

In [23]:
b.values #displays values of the dictionary

array([1, 2, 3], dtype=int64)

In [28]:
list_data=['2019-01-02',3.14,'abc',100,True]

In [29]:
pd.Series(list_data)

0    2019-01-02
1          3.14
2           abc
3           100
4          True
dtype: object

In [30]:
c=pd.Series(list_data)

In [31]:
c.index

RangeIndex(start=0, stop=5, step=1)

In [32]:
c.values

array(['2019-01-02', 3.14, 'abc', 100, True], dtype=object)

In [33]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [34]:
a.values

array(['male', 'female', 'male', 'male', 'female', 'female'], dtype=object)

In [37]:
pd.DataFrame({"name":['Braund','Mr.Harris','Allen'],
             "age":[22,35,58],
              "sex":['male','male','female']})

name  age     sex
0     Braund   22    male
1  Mr.Harris   35    male
2      Allen   58  female

In [49]:
d=pd.DataFrame({"name":['Braund','Mr.Harris','Allen'],
             "age":[22,35,58],
              "sex":['male','male','female']})

In [50]:
d

name  age     sex
0     Braund   22    male
1  Mr.Harris   35    male
2      Allen   58  female

In [51]:
d.age

0    22
1    35
2    58
Name: age, dtype: int64

In [52]:
d.name

0       Braund
1    Mr.Harris
2        Allen
Name: name, dtype: object

In [53]:
d.sex

0      male
1      male
2    female
Name: sex, dtype: object

In [54]:
type(d)

pandas.core.frame.DataFrame

In [55]:
d['age'][1]

35

In [56]:
d['name'][2]

'Allen'

In [58]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [59]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [60]:
df[0]

0    1
1    4
2    7
Name: 0, dtype: int64

In [61]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [62]:
df[0][1]

4

In [65]:
eye=pd.Series(
    [220,2155,93,64],
index=['brown','blue','hazel','green'],
name='eye_color'
)

In [66]:
eye

brown     220
blue     2155
hazel      93
green      64
Name: eye_color, dtype: int64

In [68]:
eye.index

Index(['brown', 'blue', 'hazel', 'green'], dtype='object')

In [69]:
eye.sort_values()

green      64
hazel      93
brown     220
blue     2155
Name: eye_color, dtype: int64

In [71]:
eye.sort_index()

blue     2155
brown     220
green      64
hazel      93
Name: eye_color, dtype: int64

In [73]:
eye.unique()

array([ 220, 2155,   93,   64], dtype=int64)

In [74]:
eye.nunique()

4

In [81]:
my_data2=[220,215,93,64,64]

In [82]:
eye2=pd.Series(data=my_data2,index=['brown','blue','blue','hazel','green'])

In [83]:
eye2

brown    220
blue     215
blue      93
hazel     64
green     64
dtype: int64

In [84]:
eye2.unique()

array([220, 215,  93,  64], dtype=int64)

In [85]:
eye2.nunique()

4

In [86]:
eye2.value_counts()

64     2
220    1
215    1
93     1
Name: count, dtype: int64

In [87]:
 ser=pd.Series([0,10,20,30,40],index=['a','b','c','d','e'])

In [88]:
ser

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [93]:
ser.iloc[1]

10

In [92]:
ser.iloc[b]

b    10
c    20
d    30
dtype: int64

In [91]:
ser[1:3]

b    10
c    20
dtype: int64

In [94]:
ser[1:]

b    10
c    20
d    30
e    40
dtype: int64

In [95]:
ser[1:4]

b    10
c    20
d    30
dtype: int64

In [110]:
 ser1=pd.Series([0,10,20,30,40],index=[0,1,2,3,4])
 ser2=pd.Series([0,20,30,40,50],index=[4,3,2,1,0])

In [111]:
ser1

0     0
1    10
2    20
3    30
4    40
dtype: int64

In [112]:
ser2

4     0
3    20
2    30
1    40
0    50
dtype: int64

In [113]:
add=ser1+ser2

In [114]:
add

0    50
1    50
2    50
3    50
4    40
dtype: int64

In [115]:
sub=ser2-ser1

In [116]:
sub

0    50
1    30
2    10
3   -10
4   -40
dtype: int64

In [117]:
mul=ser1*ser2

In [118]:
mul

0      0
1    400
2    600
3    600
4      0
dtype: int64

In [119]:
div=ser2/ser1

In [120]:
div

0         inf
1    4.000000
2    1.500000
3    0.666667
4    0.000000
dtype: float64

In [121]:
mod=ser2//ser1

In [122]:
mod

0    inf
1    4.0
2    1.0
3    0.0
4    0.0
dtype: float64

In [123]:
sum(ser1)

100

In [125]:
ser1.sum()

100

In [127]:
ser1.mean()

20.0

In [128]:
ser1.var()

250.0

In [130]:
ser1.median()

20.0

In [131]:
ser1.std()

15.811388300841896

In [132]:
ser1.min()

0

In [133]:
ser1.max()

40

In [134]:
ser2.min()

0

In [135]:
ser2.max()

50

In [140]:
ser2.argmax() #returns index of max value

4

In [141]:
ser2.argmin() #returns index of min value

0

In [142]:
ser1.sort_values()

0     0
1    10
2    20
3    30
4    40
dtype: int64

lambda function

In [143]:
ser_height=pd.Series([160,170,180],name='height')

In [147]:
plus_10=lambda x:x+100

In [148]:
plus_10(5)

105

In [154]:
ser_height.apply(lambda x:x+100)

0    260
1    270
2    280
Name: height, dtype: int64

In [157]:
df=pd.read_csv('Iris.csv')

In [158]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [161]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [166]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [167]:
type(df)

pandas.core.frame.DataFrame

In [168]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [174]:
df.columns=['index', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species']

In [175]:
df.columns

Index(['index', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
       'PetalWidthCm', 'Species'],
      dtype='object')

In [176]:
df

index  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0        1            5.1           3.5            1.4           0.2   
1        2            4.9           3.0            1.4           0.2   
2        3            4.7           3.2            1.3           0.2   
3        4            4.6           3.1            1.5           0.2   
4        5            5.0           3.6            1.4           0.2   
..     ...            ...           ...            ...           ...   
145    146            6.7           3.0            5.2           2.3   
146    147            6.3           2.5            5.0           1.9   
147    148            6.5           3.0            5.2           2.0   
148    149            6.2           3.4            5.4           2.3   
149    150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [180]:
df.index[1]

1

In [187]:
df['index'],['SepalLengthCm']

(0        1
 1        2
 2        3
 3        4
 4        5
       ... 
 145    146
 146    147
 147    148
 148    149
 149    150
 Name: index, Length: 150, dtype: int64,
 ['SepalLengthCm'])

In [183]:
df.iloc[0]

index                      1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [177]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [188]:
df[['index','SepalLengthCm']]

index  SepalLengthCm
0        1            5.1
1        2            4.9
2        3            4.7
3        4            4.6
4        5            5.0
..     ...            ...
145    146            6.7
146    147            6.3
147    148            6.5
148    149            6.2
149    150            5.9

[150 rows x 2 columns]

In [192]:
m=pd.DataFrame({"name":['tom','alice'],
                "age":[15,10],
                "sex":['male','female'],
                "school":['middle','elementary']})

In [193]:
m

name  age     sex      school
0    tom   15    male      middle
1  alice   10  female  elementary

In [194]:
m.index

RangeIndex(start=0, stop=2, step=1)

In [195]:
m.index=['student 1','student 2']

In [196]:
m

name  age     sex      school
student 1    tom   15    male      middle
student 2  alice   10  female  elementary

In [197]:
m.rename(columns={'name':'stud_name'})

stud_name  age     sex      school
student 1       tom   15    male      middle
student 2     alice   10  female  elementary

In [199]:
m

name  age     sex      school
student 1    tom   15    male      middle
student 2  alice   10  female  elementary

In [200]:
m.rename(columns={'name':'stud_name'},inplace=True)

In [201]:
m

stud_name  age     sex      school
student 1       tom   15    male      middle
student 2     alice   10  female  elementary