In [61]:
import numpy as np

In [62]:
np.__version__

'1.26.4'

In [63]:
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [64]:
arr1=np.array([1,3,5,7,9])

In [65]:
type(arr1)

numpy.ndarray

In [66]:
arr2=np.array([1,3,5,7,9])

In [67]:
id(arr1)

2382430911536

In [68]:
id(arr2)           

2382430912304

In [69]:
arr3=arr1

In [70]:
id(arr3)

2382430911536

In [71]:
arr4=np.copy(arr1)

arr4

In [72]:
id(arr4)

2382430912016

creating array with tuples

In [73]:
type((1,3,5,7,9))

tuple

In [74]:
np.array((1,3,5,7,9))

array([1, 3, 5, 7, 9])

creating array  with dictionaries

In [75]:
type({'one':1,'two':2,'three':3})

dict

In [76]:
np.array({'one':1,'two':2,'three':3})

array({'one': 1, 'two': 2, 'three': 3}, dtype=object)

In [77]:
{1,1,2,2,2,3,3,4,4,4}

{1, 2, 3, 4}

In [78]:
type({1,1,2,2,2,3,3,4,4,4})

set

In [79]:
np.array({1,1,2,2,2,3,3,4,4,4})

array({1, 2, 3, 4}, dtype=object)

In [80]:
arr5=np.array([1,2,3,4,5])

add 5 to all elements to the array

In [81]:
print(arr5+5)

[ 6  7  8  9 10]


multiply by 2 for all elements in the array

In [82]:
print(arr5*2)

[ 2  4  6  8 10]


creating array with a range

In [83]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
[i for i in np.arange(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [85]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [88]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [89]:
arr6=np.arange(7,71,7)

In [90]:
print(arr6)

[ 7 14 21 28 35 42 49 56 63 70]


length of elements in array

In [91]:
len(arr6)

10

In [92]:
arr6.size

10

In [93]:
type(arr6)

numpy.ndarray

In [94]:
arr7=np.array([111,2.3,True])

In [95]:
type(arr7[0])

numpy.float64

In [96]:
type(arr7[1])

numpy.float64

In [97]:
type(arr7[2])

numpy.float64

In [98]:
type(arr7)

numpy.ndarray

In [99]:
a=1.2
print(int(a))

1


In [100]:
2**8

256

In [101]:
np.array(['apple','banana','strawberry'])

array(['apple', 'banana', 'strawberry'], dtype='<U10')

In [102]:
arr8=np.array(['apple','banana','strawberry'])

In [103]:
type(arr8)

numpy.ndarray

creating arrays with the linspace function

In [104]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [105]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

2 dimensional array

In [106]:
arr9=[[2,3],[7,9]]

In [107]:
a2=np.array(arr9)
print(a2)

[[2 3]
 [7 9]]


In [108]:
val=[[1,2,3],[2,3,5],[4,5,7]]

In [109]:
a1=np.array(val)
print(a1)

[[1 2 3]
 [2 3 5]
 [4 5 7]]


In [110]:
a1.T

array([[1, 2, 4],
       [2, 3, 5],
       [3, 5, 7]])

In [111]:
a1.ndim

2

In [112]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [113]:
a2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a2.ndim

3

In [114]:
a1[1][2]

5

In [115]:
a2[0][1]

array([3, 4])

In [116]:
a2[0][0][0]


1

In [117]:
a2[0][1][1]

4

In [118]:
a2[0,1,1]

4

In [119]:
a3=np.zeros((2,3))

In [120]:
type(a3)

numpy.ndarray

In [121]:
print(a3)

[[0. 0. 0.]
 [0. 0. 0.]]


properties of numpy array

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a.ndim #dimension of array

2

In [5]:
a.size #number of elements

9

In [6]:
a.shape #number of rows and columns

(3, 3)

In [7]:
a5=np.array([1,2,3,4])

In [8]:
a5.shape

(4,)

In [9]:
a6=np.arange(15)

In [10]:
print(a6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
a6.reshape((3,5)) #reshape divides 1-d array to 2-d having 3 rows and 5 columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
a7=np.arange(15)

In [13]:
print(a7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
a7.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

random numbers

In [15]:
data=np.random.randn(2,3) #gets random numbers from gaussian curve or bell shape curve

In [16]:
data

array([[-0.50220496,  0.06239544, -1.98969635],
       [ 0.95503175, -0.71423468,  1.95563799]])

In [17]:
np.mean(data)

-0.03884513687894272

In [18]:
values=np.random.randn(2,5)

In [19]:
values

array([[ 0.64935246,  0.37268346, -0.32414093, -0.83760148,  0.48414957],
       [ 0.71809966, -0.11459143, -0.96475794,  0.59603757, -0.78427823]])

In [20]:
np.mean(values)

-0.020504730526857983

In [21]:
data1=np.random.randn(100,100)

In [22]:
data1

array([[ 1.76649231,  1.38147598, -0.20256015, ..., -1.05591174,
         0.53380501, -2.09691923],
       [ 0.92777099, -0.03792306, -1.29102989, ...,  0.72191346,
         1.65431089, -0.47635072],
       [ 0.17381669, -0.91081029,  0.1323787 , ...,  0.94400269,
         0.13094379,  1.46693527],
       ...,
       [ 1.23435546, -0.01382089, -0.12345063, ..., -0.18973542,
         0.42534946, -0.05363438],
       [-0.11325164,  1.13423524, -0.56310395, ...,  1.37092478,
        -0.45245031,  0.63912065],
       [-0.64662149,  0.29841653, -0.2935562 , ..., -0.48140024,
        -0.02458534, -0.35060334]])

In [23]:
np.mean(data1)

0.003531021979890141

compare python lists vs numpy array

In [24]:
np.arange(10000000)

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [25]:
list(range(10000000))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [33]:
%time for i in range(1000):np.arange(10000000)*2

CPU times: total: 24.1 s
Wall time: 25 s


In [272]:
%time for i in range(1000):list(range(10000000))*2

KeyboardInterrupt: 

In [26]:
b=np.array([1,2,3,4])

In [27]:
b

array([1, 2, 3, 4])

In [28]:
c=np.append(a,[5,6,7])

In [29]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 6, 7])

In [30]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
d.ndim

2

In [32]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
d1=np.append(d,[[10,11,12]],axis=0) #adding a row (axis=0)

In [45]:
d1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
d2=np.append(d1,[[1],[4],[7],[10]],axis=1) #adding a column (axis=1)

In [47]:
d2

array([[ 1,  2,  3,  1],
       [ 4,  5,  6,  4],
       [ 7,  8,  9,  7],
       [10, 11, 12, 10]])

delete an element from array

In [48]:
a=np.array([[1,2,3],[4,5,6]])

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.delete(a,0)

array([2, 3, 4, 5, 6])

In [51]:
a1=np.delete(a,0)

In [52]:
a1

array([2, 3, 4, 5, 6])

In [53]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.delete(a,0,axis=0) #delete row

array([[4, 5, 6]])

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.delete(a,0,axis=1) #delete column

array([[2, 3],
       [5, 6]])

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6]])

basic mathematical operation on arrays

In [122]:
z1=np.array([1,2,3,4,5])

In [123]:
z1

array([1, 2, 3, 4, 5])

In [124]:
z2=np.array([6,7,8,9,10])

In [125]:
z2

array([ 6,  7,  8,  9, 10])

In [128]:
z1+z2

array([ 7,  9, 11, 13, 15])

In [129]:
z1-z2

array([-5, -5, -5, -5, -5])

In [130]:
z2-z1

array([5, 5, 5, 5, 5])

In [131]:
z1*z2

array([ 6, 14, 24, 36, 50])

In [132]:
z1/z2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [133]:
z1//z2

array([0, 0, 0, 0, 0])

In [134]:
z2**z1

array([     6,     49,    512,   6561, 100000])

In [135]:
v=np.array([1,2,3])

In [136]:
v

array([1, 2, 3])

In [148]:
v*3 #multiplies 3 for all elements in the  numpy array

array([3, 6, 9])

In [149]:
v1=[1,2,3]

In [150]:
v1

[1, 2, 3]

In [151]:
v1*3 #repeats the elements in the array 3 times

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [154]:
s=[1,2,3]
f=[4,5,6]

In [155]:
s+f

[1, 2, 3, 4, 5, 6]

In [160]:
np.repeat(v,3) 

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [161]:
np.tile(v,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [162]:
g=np.arange(15)

In [176]:
h=g.reshape((3,5))

In [177]:
m=np.tile(h,3)

In [178]:
m

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

In [179]:
v**2

array([1, 4, 9])

In [180]:
z2/(z2**2)

array([0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

vectorization

In [187]:
z1==z2

array([False, False, False, False, False])

In [188]:
z1!=z2

array([ True,  True,  True,  True,  True])

In [189]:
z1>z2

array([False, False, False, False, False])

In [190]:
z2>z1

array([ True,  True,  True,  True,  True])

In [191]:
v>1

array([False,  True,  True])

In [192]:
z1==1

array([ True, False, False, False, False])

In [193]:
np.sqrt(v)

array([1.        , 1.41421356, 1.73205081])

In [211]:
x=np.arange(1,11)

In [212]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [215]:
x_mean=x.mean()

In [234]:
x_mean

5.5

In [235]:
sum

55

In [236]:
x_mean-x

array([ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5])

In [237]:
z=(x_mean-x)**2

In [238]:
ans=z.sum()

In [239]:
ans

82.5

In [240]:
var=ans/x.size

In [241]:
var

8.25

In [242]:
standard_deviation=np.sqrt(var)

In [243]:
standard_deviation

2.8722813232690143

In [248]:
x1=x.cumsum()

In [251]:
x1

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [249]:
x1.max()

55

In [250]:
x1.min()

1

In [253]:
x.max()

10

In [254]:
x.min()

1

In [4]:
import numpy as np

statistical methods of numpy array

In [7]:
n=np.arange(15)

In [8]:
n1=n.reshape(3,5)

In [9]:
np.mean(n1,axis=0)

array([5., 6., 7., 8., 9.])

In [10]:
np.mean(n1,axis=1)

array([ 2.,  7., 12.])

random numbers in numpy

In [11]:
np.random.randint(10)

3

In [12]:
np.random.randint(1,11)

9

In [13]:
np.random.randint(1,11,2)

array([6, 4])

In [14]:
np.random.seed(123)
a=np.random.randint(1,11,size=1000)

In [15]:
a

array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9,  1,  8, 10,  4,  5,  7,
        2,  6,  7,  3,  2,  9,  4,  6,  1,  3,  7,  3,  5,  5,  7,  4,  1,
        7,  5,  8,  7,  8,  2,  6,  8, 10,  3,  5,  9,  2,  3,  2,  2,  4,
        6, 10,  1,  9,  2,  7,  4,  4,  6, 10,  8, 10,  3,  4,  4,  4,  9,
        7, 10,  8,  7,  4, 10,  7,  7,  7,  2,  4,  5,  4,  2,  1,  6,  9,
        7,  9, 10,  2,  1,  4,  2,  4,  5,  8,  7,  2,  5,  4,  4,  8,  7,
        9,  7,  5,  5,  8,  1,  1, 10,  9,  9,  5,  9,  7,  2,  7,  9,  8,
       10,  2,  8,  2,  8, 10,  9,  8,  2,  4,  2,  9,  8,  6,  2,  3,  6,
        3,  3, 10,  4,  3,  7,  8, 10,  2,  4,  9,  4,  8, 10, 10,  4,  4,
        6,  7,  1,  9,  8,  8,  5,  5,  6,  1,  9, 10,  3,  6,  2,  6, 10,
        3,  5,  4,  1,  4,  8,  8,  3,  6,  2,  8,  6, 10,  2,  3,  9,  6,
        1, 10,  4,  4,  4,  2,  8,  7,  4,  2,  8,  3,  7,  6, 10,  9, 10,
        5,  8,  9,  6, 10

In [16]:
np.random.randint(123)
a1=np.random.randint(1,11,size=20)
a1

array([ 2,  7,  6,  4,  2,  6,  9,  9,  6,  6,  5, 10,  4,  4,  5,  2, 10,
        6, 10,  8])

In [17]:
a1.size

20

In [18]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.median(a)

5.0

In [20]:
np.sum(a)

5485

In [21]:
np.var(a)

8.193775

In [24]:
np.round(np.var(a),2)

8.19

In [25]:
np.std(a)

2.862477074144001

In [26]:
np.round(np.std(a),3)

2.862

In [27]:
a.max()

10

In [28]:
a.min()

1

In [34]:
 c=np.arange(-10,10)

In [35]:
c

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [40]:
c.argmax() #returns location

19

In [41]:
c.argmin() #returns location

0

working on matrices

In [47]:
g=np.array([[1,2],[4,5]])

In [51]:
g

array([[1, 2],
       [4, 5]])

In [52]:
h=np.array([[1,2],[4,5]])

In [53]:
h

array([[1, 2],
       [4, 5]])

In [54]:
g*h

array([[ 1,  4],
       [16, 25]])

In [56]:
np.dot(g,h)

array([[ 9, 12],
       [24, 33]])

In [58]:
g.dot(h)

array([[ 9, 12],
       [24, 33]])

In [59]:
np.transpose(g)

array([[1, 4],
       [2, 5]])

In [60]:
np.transpose(h)

array([[1, 4],
       [2, 5]])

In [61]:
g.transpose()

array([[1, 4],
       [2, 5]])

In [62]:
g.T

array([[1, 4],
       [2, 5]])

In [64]:
np.linalg.inv(g)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [65]:
np.linalg.inv(h)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [66]:
np.linalg.det(g)

-2.9999999999999996

In [67]:
np.linalg.det(h)

-2.9999999999999996

In [68]:
A=np.array([[0,2],[1,3]])

In [69]:
np.linalg.det(A)

-2.0

numpy indexing and slicing

In [70]:
import numpy as numpy

In [71]:
a=np.array([0,1,2,3])

In [89]:
b=np.array([[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]])

In [90]:
a[0]

0

In [91]:
b[0]

array([0, 1, 2, 3])

In [92]:
b[0][1]

1

In [93]:
a1=np.array([0,10,20,30,40,50])
a1[5]

50

In [94]:
a1[5]=70

In [95]:
a1

array([ 0, 10, 20, 30, 40, 70])

In [99]:
b=np.array([[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]])

In [100]:
b[0]=[9,8,7,6]

In [101]:
b

array([[ 9,  8,  7,  6],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
b[0][1]=78

In [103]:
b

array([[ 9, 78,  7,  6],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
a[0]

0

In [111]:
a1=np.array([0,10,20,30,40,50])
a1[[1,3,4]]

array([10, 30, 40])

In [112]:
a2=np.arange(10,100,10).reshape(3,3)

In [113]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [114]:
a2[2,2]=95

In [115]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [117]:
a2[0,2]

30

In [120]:
a2[2]=np.array([45,55,65])

In [121]:
a2 

array([[10, 20, 30],
       [40, 50, 60],
       [45, 55, 65]])

In [122]:
a2[[0,2],[0,1]]

array([10, 55])

In [124]:
a=np.array([1,2,3,4,5,6])

In [125]:
a[a>3]

array([4, 5, 6])

In [126]:
a[a%2==0]

array([2, 4, 6])

array slicing

In [127]:
b1=np.array([0,10,20,30,40,50])

In [128]:
b1[1:4]

array([10, 20, 30])

In [129]:
b1[2:5]

array([20, 30, 40])

In [130]:
b1[ :3]

array([ 0, 10, 20])

In [131]:
b1[2:]

array([20, 30, 40, 50])

In [132]:
arr2d=np.arange(1,10).reshape(3,3)

In [133]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
arr2d[2:]

array([[7, 8, 9]])

In [136]:
arr2d[1:2]

array([[4, 5, 6]])

In [137]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [138]:
arr2d[:2,2:]

array([[3],
       [6]])

In [139]:
arr2d[:1,2:]

array([[3]])

In [142]:
arr2d[1,:2]

array([4, 5])

In [143]:
arr2d[1,1:3]

array([5, 6])

In [144]:
arr2d[1,1:]

array([5, 6])

In [150]:
arr2d[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [151]:
arr2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [152]:
arr2d[:2,2]

array([3, 6])

In [154]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [159]:
arr2d[:,2:3]

array([[3],
       [6],
       [9]])

In [160]:
arr2d[:,1:2]

array([[2],
       [5],
       [8]])

In [161]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [162]:
arr2d[2]

array([7, 8, 9])

In [163]:
arr2d[2,:]

array([7, 8, 9])

In [164]:
arr2d[2:,:]

array([[7, 8, 9]])

In [165]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [166]:
arr2d[1,2:]

array([6])

In [167]:
arr2d[1:2,:2]

array([[4, 5]])

selecting in boolean values

In [3]:
import numpy as np

In [4]:
names=np.array(['bob','joe','tom','bob','tom','joe','joe'])

In [5]:
names

array(['bob', 'joe', 'tom', 'bob', 'tom', 'joe', 'joe'], dtype='<U3')

In [6]:
names=='bob'

array([ True, False, False,  True, False, False, False])

In [8]:
names[names=='bob']

array(['bob', 'bob'], dtype='<U3')

In [9]:
np.empty((8,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr=np.empty((8,4))

In [11]:
for i in range(8):
    arr[i]=i

In [12]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [13]:
arr[[2,1,4]]

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [4., 4., 4., 4.]])

In [14]:
arr[[-3,-5]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [15]:
m=np.arange(20)

In [16]:
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
m.size

20

In [23]:
for i in m:
    if m[i]%5==0:
        print(m[i])  

0
5
10
15


In [24]:
arr2=np.arange(20)

In [27]:
arr5=(arr2%5==0)

In [28]:
arr2[arr5]

array([ 0,  5, 10, 15])

In [31]:
arr6=(arr2>10)

In [32]:
arr2[arr6]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
arr2[arr5 & arr6]

array([15])

In [36]:
arr2[arr5 | arr6]

array([ 0,  5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])